[tox]
skipsdist = True
envlist = py310,py311,py312,py313

[testenv:{py310,py311,py312,py313}]
description = adapter plugin integration and unit testing
skip_install = true
passenv =
    DBT_DEBUG
commands =
	{envpython} -m pytest -n auto {posargs}
deps =
  -rdev-requirements.txt
  -e.
