# This workflow will run unit, functional tests, code quality checks and verifies the build on all code committed to the repository.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: dbt-impala tests
on:
  push:
    branches:
      - master
      - impala-ci-cd-firstcut
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**/*.md"

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the source code"
        uses: actions/checkout@v4

      - name: "Install Python"
        uses: actions/setup-python@v5

      - name: "Install dev requirements"
        run: pip install -r dev_requirements.txt

      - name: "Run pre-commit checks"
        run: pre-commit run --all-files
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: pip install tox
      - name: Run tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py

      - name: Run dbt-impala tests on python ${{ matrix.python }}
        run: make test_all_python_versions
